### ISSUE TITLE
cant get client.exe to work

### ISSUE THREAD

**Issue by r-lyeh-archived** [dwilliamson/NativeWebSocketRender#1]
client is always silent and showing no info.
is client expecting the server to send a different (outdated?) protocol maybe?

PS: on the other hand, .html client works flawlessly. congrats : )

**Comment by dwilliamson** [comment]
Yeah, that's expected. The server exe must be rebuilt depending on what client type you're expecting to connect. See this line here:

https://github.com/dwilliamson/NativeWebSocketRender/blob/master/Server/Server.cpp#L140

**Comment by r-lyeh-archived** [comment]
oh gawd

**Comment by r-lyeh-archived** [comment]
ty : )
